name: Check Notes

on:
  workflow_dispatch:

jobs:
  check-notes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get Notes from Main Branch
        run: |
          NOTES_URL="https://api.github.com/repos/shijiuliyaoxian/ceshi/contents/notes.md?ref=main"
          RESPONSE=$(curl -s $NOTES_URL)
          CONTENT=$(echo $RESPONSE | jq -r '.content' | base64 --decode)
          echo "## Notes from Main Branch" > notes_output.md
          echo "$CONTENT" >> notes_output.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Notes Output
        uses: actions/upload-artifact@v2
        with:
          name: notes-output
          path: notes_output.md
