name: Build and Deploy Notes Viewer

on:
  push:
    branches:
      - main
      - feature/view-main-notes

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
async function fetchMainBranchNotes() {
  const response = await fetch('https://api.github.com/repos/shijiuliyaoxian/biji/contents/notes.md?ref=main');
  const data = await response.json();
  const content = atob(data.content);
  document.getElementById('notes').innerText = content;
}

fetchMainBranchNotes();
